services:
  rewardsapp-fe:
    container_name: rewardsapp-fe-container
    build: .
    image: rewardsapp-fe:v1
    ports:
      - 5000:5000
    expose:
      - 5000
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
